/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Page;

import java.text.DateFormat;
import javax.swing.JOptionPane;
import Page.sms.Staff;
import java.awt.Color;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class StaffForms extends javax.swing.JFrame {
    
    private ArrayList<Staff> staff;
    private ArrayList<Staff> deactive;

    /**
     * Creates new form StaffForms
     */
    public StaffForms() {
        initComponents();
        
        staff = new ArrayList<Staff>();
        deactive = new ArrayList<Staff>();
        
        populateArrayList();
        populateDeactiveArrayList();
    }
    
    public void saveMembersToFile(){
        try(FileOutputStream file = new FileOutputStream("Staff.dat");
           ObjectOutputStream outputFile = new ObjectOutputStream(file)){
           
           for(int i=0;i<staff.size();i++){
               outputFile.writeObject(staff.get(i));
           }
           JOptionPane.showMessageDialog(null,"Successfully Saved!");
        }
        catch(IOException e){
           // JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    
    public void populateArrayList(){    
        try(FileInputStream file2 = new FileInputStream("Staff.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2)){
            boolean endOfFile = false;
            
            while(!endOfFile){
                try{
                   staff.add((Staff)inputFile2.readObject()); 
                }
                catch(EOFException e){
                   endOfFile = true;
                }
                catch(Exception e){
                   // JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(IOException e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }

    public void saveDeactiveEmployeesToFile(){
        try(FileOutputStream file = new FileOutputStream("DeactivatEmp.dat");
           ObjectOutputStream outputFile = new ObjectOutputStream(file)){
           
           for(int i=0;i<deactive.size();i++){
               
               outputFile.writeObject(deactive.get(i));
           }
           JOptionPane.showMessageDialog(null,"Successfully Deactivated!");
     
        }
        catch(IOException e){
           // JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    
    public void populateDeactiveArrayList(){    
        try(FileInputStream file2 = new FileInputStream("DeactivatEmp.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2)){
            boolean endOfFile = false;
            while(!endOfFile){
                
                try{
                   deactive.add((Staff)inputFile2.readObject()); 
                }
                catch(EOFException e){
                   endOfFile = true;
                }
                catch(Exception e){
                   // JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(IOException e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    public void saveEditMembersToFile(){
        try(FileOutputStream file = new FileOutputStream("Staff.dat");
           ObjectOutputStream outputFile = new ObjectOutputStream(file)){
           
           for(int i=0;i<staff.size();i++){
               outputFile.writeObject(staff.get(i));
           }
           JOptionPane.showMessageDialog(null,"Successfully Edited!");
        }
        catch(IOException e){
           // JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Search = new javax.swing.JLabel();
        SearchEmp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        GLine = new javax.swing.JLabel();
        addemp = new javax.swing.JLabel();
        addempLine = new javax.swing.JLabel();
        AddEmp = new javax.swing.JButton();
        EditLine = new javax.swing.JLabel();
        delLine = new javax.swing.JLabel();
        SearchLine = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editEmp = new javax.swing.JLabel();
        Delemp = new javax.swing.JLabel();
        generateList = new javax.swing.JLabel();
        GenerateList = new javax.swing.JButton();
        DeleteEmp = new javax.swing.JButton();
        EditStd = new javax.swing.JButton();
        StatisticReport = new javax.swing.JButton();
        lgout = new javax.swing.JLabel();
        Logout1 = new javax.swing.JButton();
        stf = new javax.swing.JLabel();
        StudentPortal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        HideBar = new javax.swing.JPanel();
        Forms = new javax.swing.JTabbedPane();
        AddEmpolyee = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FatherName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Surname1 = new javax.swing.JTextField();
        FatherCNIC1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        GMALE = new javax.swing.JRadioButton();
        GFEMALE = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        SalaryNew = new javax.swing.JTextField();
        Contact = new javax.swing.JLabel();
        Surname2 = new javax.swing.JTextField();
        Nationality = new javax.swing.JTextField();
        rel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SaveData = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Degree = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        Designation = new javax.swing.JComboBox<>();
        DeactiveEmployee = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EmployeeID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        DeleteEmployeeButton = new javax.swing.JButton();
        SearchEmployee = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        SearchEmployeeID = new javax.swing.JTextField();
        SearchEmpID = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        SC = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        SearchCNIC = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        EditEmplpyee = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        NameEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TeacherID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        FatherNameEdit = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        SurnameEdit = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CNIC = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        DOBEdit = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        GMALE1 = new javax.swing.JRadioButton();
        GFEMALE1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        Degree1 = new javax.swing.JComboBox<>();
        ContactEdit = new javax.swing.JTextField();
        Nationality1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Contact1 = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        relEdit = new javax.swing.JComboBox<>();
        SaveEditedData = new javax.swing.JButton();
        GenerateListEmployee = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ReligionCheck = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        Designation1 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        NameChecked = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        FatherNameChecked1 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        SalaryChecked1 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        ContactChecked1 = new javax.swing.JCheckBox();
        Generate = new javax.swing.JButton();
        StatisticalReport = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        GenederRatio = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        DegreeRatio = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        SalaryRtio = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        ReligionRatio = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Forms");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("              MENU");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 50));

        Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("       SEARCH EMPLOYEE");
        Search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        SearchEmp.setBackground(new java.awt.Color(51, 51, 51));
        SearchEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        SearchEmp.setForeground(new java.awt.Color(102, 102, 102));
        SearchEmp.setToolTipText("");
        SearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmpActionPerformed(evt);
            }
        });
        jPanel1.add(SearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("        STATISTIC REPORTS");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 50));

        GLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        GLine.setForeground(new java.awt.Color(204, 204, 204));
        GLine.setText("_________________________");
        jPanel1.add(GLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, -1));

        addemp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addemp.setForeground(new java.awt.Color(255, 255, 255));
        addemp.setText("          ADD EMPLOYEE");
        addemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 50));

        addempLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        addempLine.setForeground(new java.awt.Color(204, 204, 204));
        addempLine.setText("_________________________");
        jPanel1.add(addempLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, -1));

        AddEmp.setBackground(new java.awt.Color(51, 51, 51));
        AddEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        AddEmp.setForeground(new java.awt.Color(102, 102, 102));
        AddEmp.setToolTipText("");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });
        jPanel1.add(AddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 50));

        EditLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        EditLine.setForeground(new java.awt.Color(204, 204, 204));
        EditLine.setText("_________________________");
        jPanel1.add(EditLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 200, -1));

        delLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        delLine.setForeground(new java.awt.Color(204, 204, 204));
        delLine.setText("_________________________");
        jPanel1.add(delLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, -1));

        SearchLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        SearchLine.setForeground(new java.awt.Color(204, 204, 204));
        SearchLine.setText("_________________________");
        jPanel1.add(SearchLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        jLabel11.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("_________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 200, -1));

        editEmp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editEmp.setForeground(new java.awt.Color(255, 255, 255));
        editEmp.setText("          EDIT EMPLOYEE");
        editEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(editEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 50));

        Delemp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Delemp.setForeground(new java.awt.Color(255, 255, 255));
        Delemp.setText("    DEACTIVATE EMPLOYEE");
        Delemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Delemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 50));

        generateList.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        generateList.setForeground(new java.awt.Color(255, 255, 255));
        generateList.setText("          GENERATE LIST");
        generateList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(generateList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 50));

        GenerateList.setBackground(new java.awt.Color(51, 51, 51));
        GenerateList.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        GenerateList.setForeground(new java.awt.Color(102, 102, 102));
        GenerateList.setToolTipText("");
        GenerateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateListActionPerformed(evt);
            }
        });
        jPanel1.add(GenerateList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 50));

        DeleteEmp.setBackground(new java.awt.Color(51, 51, 51));
        DeleteEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        DeleteEmp.setForeground(new java.awt.Color(102, 102, 102));
        DeleteEmp.setToolTipText("");
        DeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmpActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 50));

        EditStd.setBackground(new java.awt.Color(51, 51, 51));
        EditStd.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        EditStd.setForeground(new java.awt.Color(102, 102, 102));
        EditStd.setToolTipText("");
        EditStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStdActionPerformed(evt);
            }
        });
        jPanel1.add(EditStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 50));

        StatisticReport.setBackground(new java.awt.Color(51, 51, 51));
        StatisticReport.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        StatisticReport.setForeground(new java.awt.Color(102, 102, 102));
        StatisticReport.setToolTipText("");
        StatisticReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticReportActionPerformed(evt);
            }
        });
        jPanel1.add(StatisticReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 50));

        lgout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lgout.setForeground(new java.awt.Color(255, 255, 255));
        lgout.setText("                  Logout");
        jPanel1.add(lgout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 50));

        Logout1.setBackground(new java.awt.Color(51, 51, 51));
        Logout1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Logout1.setForeground(new java.awt.Color(102, 102, 102));
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 50));

        stf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        stf.setForeground(new java.awt.Color(255, 255, 255));
        stf.setText("         STUDENT PORTAL");
        jPanel1.add(stf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 50));

        StudentPortal.setBackground(new java.awt.Color(51, 51, 51));
        StudentPortal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        StudentPortal.setForeground(new java.awt.Color(102, 102, 102));
        StudentPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPortalActionPerformed(evt);
            }
        });
        jPanel1.add(StudentPortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 50));

        jLabel13.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("_________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, -1));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/Menu (1).png"))); // NOI18N
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 550));

        HideBar.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout HideBarLayout = new javax.swing.GroupLayout(HideBar);
        HideBar.setLayout(HideBarLayout);
        HideBarLayout.setHorizontalGroup(
            HideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        HideBarLayout.setVerticalGroup(
            HideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(HideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 750, 50));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("  Add Employee");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("First Name:");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        FirstName.setToolTipText("");
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        jPanel8.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 140, 30));

        LastName.setToolTipText("");
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        jPanel8.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 210, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Father Name:");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        FatherName.setToolTipText("");
        FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameActionPerformed(evt);
            }
        });
        jPanel8.add(FatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Surname:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 140, 30));

        Surname1.setToolTipText("");
        Surname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Surname1ActionPerformed(evt);
            }
        });
        jPanel8.add(Surname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 210, 30));

        FatherCNIC1.setToolTipText("");
        FatherCNIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherCNIC1ActionPerformed(evt);
            }
        });
        jPanel8.add(FatherCNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("CNIC:");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Date of Birth:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 140, 30));

        DOB.setDateFormatString("dd/MM/yyyy");
        jPanel8.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 210, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Gender:");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 30));

        GMALE.setText("Male");
        jPanel8.add(GMALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        GFEMALE.setText("Female");
        GFEMALE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GFEMALEActionPerformed(evt);
            }
        });
        jPanel8.add(GFEMALE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Salary:");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 30));

        SalaryNew.setToolTipText("");
        SalaryNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryNewActionPerformed(evt);
            }
        });
        jPanel8.add(SalaryNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        Contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Contact.setText("Contact #:");
        jPanel8.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 140, 30));

        Surname2.setToolTipText("");
        Surname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Surname2ActionPerformed(evt);
            }
        });
        jPanel8.add(Surname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, 30));

        Nationality.setToolTipText("");
        Nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityActionPerformed(evt);
            }
        });
        jPanel8.add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 210, 30));

        rel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Hindu", "Christianity", "Other" }));
        jPanel8.add(rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Designation/Area:");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Nationality:");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, 30));

        SaveData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/folder.png"))); // NOI18N
        SaveData.setText("Save");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });
        jPanel8.add(SaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 120, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Degree:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 100, 30));

        Degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "MS", "Mphil", "PhD" }));
        Degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegreeActionPerformed(evt);
            }
        });
        jPanel8.add(Degree, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Religion:");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        Designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrative", "Primary Teacher", "Middle Teacher", "Account Depart:", "Examination Depart:", "Manual Staff", "Driver" }));
        jPanel8.add(Designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 160, 30));

        javax.swing.GroupLayout AddEmpolyeeLayout = new javax.swing.GroupLayout(AddEmpolyee);
        AddEmpolyee.setLayout(AddEmpolyeeLayout);
        AddEmpolyeeLayout.setHorizontalGroup(
            AddEmpolyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddEmpolyeeLayout.setVerticalGroup(
            AddEmpolyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEmpolyeeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Forms.addTab("tab2", AddEmpolyee);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeID.setToolTipText("GR-10989");
        EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIDActionPerformed(evt);
            }
        });
        jPanel2.add(EmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 30));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel20.setText("  Deactivate Employee");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel24.setText("Enter Employee ID:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 30));

        DeleteEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/exit.png"))); // NOI18N
        DeleteEmployeeButton.setText("Delete");
        DeleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 130, 40));

        javax.swing.GroupLayout DeactiveEmployeeLayout = new javax.swing.GroupLayout(DeactiveEmployee);
        DeactiveEmployee.setLayout(DeactiveEmployeeLayout);
        DeactiveEmployeeLayout.setHorizontalGroup(
            DeactiveEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeactiveEmployeeLayout.setVerticalGroup(
            DeactiveEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Forms.addTab("tab1", DeactiveEmployee);

        SearchEmployee.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setText("  Search Employee");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel28.setText("Enter Employee ID:");

        SearchEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeeIDActionPerformed(evt);
            }
        });

        SearchEmpID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchEmpID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/student.png"))); // NOI18N
        SearchEmpID.setText("Search");
        SearchEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmpIDActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("______________________________________________________________________");

        SC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setText("Enter CNIC:");

        SearchCNIC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchCNIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/student.png"))); // NOI18N
        SearchCNIC.setText("Search");
        SearchCNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCNICActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 51, 51));
        jLabel27.setText("Note: In case if you forget your Student ID, you may go for the second option of CNIC");

        javax.swing.GroupLayout SearchEmployeeLayout = new javax.swing.GroupLayout(SearchEmployee);
        SearchEmployee.setLayout(SearchEmployeeLayout);
        SearchEmployeeLayout.setHorizontalGroup(
            SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchEmployeeLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchEmployeeLayout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addGroup(SearchEmployeeLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SearchEmployeeLayout.createSequentialGroup()
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(SearchEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(SearchEmployeeLayout.createSequentialGroup()
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 61, Short.MAX_VALUE))
                .addGroup(SearchEmployeeLayout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SearchEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchCNIC))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        SearchEmployeeLayout.setVerticalGroup(
            SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchEmployeeLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchEmployeeLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(SearchEmpID)
                    .addGap(29, 29, 29)
                    .addComponent(jLabel29)
                    .addGap(58, 58, 58)
                    .addGroup(SearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(SearchCNIC)
                    .addGap(0, 156, Short.MAX_VALUE)))
        );

        Forms.addTab("tab3", SearchEmployee);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameEdit.setToolTipText("");
        NameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameEditActionPerformed(evt);
            }
        });
        jPanel4.add(NameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 210, 30));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setText("  Edit Employee");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        TeacherID.setToolTipText("");
        TeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherIDActionPerformed(evt);
            }
        });
        jPanel4.add(TeacherID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Teacher ID:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText(" Name:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 140, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Father Name:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        FatherNameEdit.setToolTipText("");
        FatherNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameEditActionPerformed(evt);
            }
        });
        jPanel4.add(FatherNameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Surname:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 140, 30));

        SurnameEdit.setToolTipText("");
        SurnameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameEditActionPerformed(evt);
            }
        });
        jPanel4.add(SurnameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 210, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("CNIC:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 30));

        CNIC.setToolTipText("");
        CNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICActionPerformed(evt);
            }
        });
        jPanel4.add(CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Date of Birth:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 140, 30));

        DOBEdit.setDateFormatString("dd/MM/yyyy");
        jPanel4.add(DOBEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 210, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Gender:");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 80, 30));

        GMALE1.setText("Male");
        jPanel4.add(GMALE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        GFEMALE1.setText("Female");
        GFEMALE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GFEMALE1ActionPerformed(evt);
            }
        });
        jPanel4.add(GFEMALE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("Degree:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 100, 30));

        Degree1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "MS", "Mphil", "PhD" }));
        Degree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Degree1ActionPerformed(evt);
            }
        });
        jPanel4.add(Degree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 210, 30));

        ContactEdit.setToolTipText("");
        ContactEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactEditActionPerformed(evt);
            }
        });
        jPanel4.add(ContactEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, 30));

        Nationality1.setToolTipText("");
        Nationality1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nationality1ActionPerformed(evt);
            }
        });
        jPanel4.add(Nationality1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 210, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Nationality:");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, 30));

        Contact1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Contact1.setText("Contact #:");
        jPanel4.add(Contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 140, 30));

        Salary.setToolTipText("");
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });
        jPanel4.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Salary:");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Religion:");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        relEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Hindu", "Christianity", "Other" }));
        jPanel4.add(relEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 30));

        SaveEditedData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveEditedData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/folder.png"))); // NOI18N
        SaveEditedData.setText("Save");
        SaveEditedData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEditedDataActionPerformed(evt);
            }
        });
        jPanel4.add(SaveEditedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 120, 50));

        javax.swing.GroupLayout EditEmplpyeeLayout = new javax.swing.GroupLayout(EditEmplpyee);
        EditEmplpyee.setLayout(EditEmplpyeeLayout);
        EditEmplpyeeLayout.setHorizontalGroup(
            EditEmplpyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmplpyeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );
        EditEmplpyeeLayout.setVerticalGroup(
            EditEmplpyeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmplpyeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        Forms.addTab("tab4", EditEmplpyee);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Generate List");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 350, 60));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Religion:");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));
        jPanel5.add(ReligionCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Select Designation/Area:");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        Designation1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrative", "Primary Teacher", "Middle Teacher", "Account Depart:", "Examination Depart:", "Manual Staff", "Driver" }));
        jPanel5.add(Designation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 160, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Name:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        jPanel5.add(NameChecked, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Father Name:");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));
        jPanel5.add(FatherNameChecked1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("Salary:");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));
        jPanel5.add(SalaryChecked1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setText("Contact#:");
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        jPanel5.add(ContactChecked1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        Generate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/Icons/job.png"))); // NOI18N
        Generate.setText("Generate");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        jPanel5.add(Generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 150, 50));

        javax.swing.GroupLayout GenerateListEmployeeLayout = new javax.swing.GroupLayout(GenerateListEmployee);
        GenerateListEmployee.setLayout(GenerateListEmployeeLayout);
        GenerateListEmployeeLayout.setHorizontalGroup(
            GenerateListEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GenerateListEmployeeLayout.setVerticalGroup(
            GenerateListEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Forms.addTab("tab5", GenerateListEmployee);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel44.setText("Generate Statistical Reports");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        GenederRatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/genderRatio.png"))); // NOI18N
        GenederRatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenederRatioActionPerformed(evt);
            }
        });
        jPanel6.add(GenederRatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, 90));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText(" Religion Ratio");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, -1));

        DegreeRatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/Degree.png"))); // NOI18N
        DegreeRatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegreeRatioActionPerformed(evt);
            }
        });
        jPanel6.add(DegreeRatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 90, 90));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText(" Dregree Ratio");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, -1));

        SalaryRtio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/salaryRatio.png"))); // NOI18N
        SalaryRtio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryRtioActionPerformed(evt);
            }
        });
        jPanel6.add(SalaryRtio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 90, 90));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText(" Gender Ratio");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 100, -1));

        ReligionRatio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/ReligiousRatio.png"))); // NOI18N
        ReligionRatio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReligionRatioActionPerformed(evt);
            }
        });
        jPanel6.add(ReligionRatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 90, 90));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("  Salary Ratio");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 100, -1));

        javax.swing.GroupLayout StatisticalReportLayout = new javax.swing.GroupLayout(StatisticalReport);
        StatisticalReport.setLayout(StatisticalReportLayout);
        StatisticalReportLayout.setHorizontalGroup(
            StatisticalReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StatisticalReportLayout.setVerticalGroup(
            StatisticalReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Forms.addTab("tab6", StatisticalReport);

        jPanel1.add(Forms, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 750, 530));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/820cce7f-0de0-4906-a734-236b8ae084c1.png"))); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
            Forms.setSelectedIndex(0);
    }//GEN-LAST:event_AddEmpActionPerformed

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Logout1ActionPerformed

    private void StudentPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPortalActionPerformed

        new Student().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_StudentPortalActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameActionPerformed

    private void Surname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Surname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Surname1ActionPerformed

    private void FatherCNIC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherCNIC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherCNIC1ActionPerformed

    private void GFEMALEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GFEMALEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GFEMALEActionPerformed

    private void SalaryNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryNewActionPerformed

    private void Surname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Surname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Surname2ActionPerformed

    private void NationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityActionPerformed

    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
        if(FirstName.getText() == null || LastName.getText() == null
                || FatherName.getText() == null || Surname1.getText() == null
                || FatherCNIC1.getText() == null || !DOB.isEnabled()
                || (!GMALE.isSelected() && !GFEMALE.isSelected()) || SalaryNew.getText() == null
                || Surname2.getText() == null || Nationality.getText() == null) {
            JOptionPane.showMessageDialog(null,"Please insert all fields");
            return;
        }
        else{
            String name = FirstName.getText().trim() +" "+LastName.getText().trim();
            if(!isValidText(name)){
                JOptionPane.showMessageDialog(null,"Invalid name");
                return;
            }
            
            String father = FatherName.getText().trim();
            if(!isValidText(father)){
                JOptionPane.showMessageDialog(null,"Invalid father name");
                return;
            }
            
            String surname = Surname1.getText().trim();
            if(!isValidText(surname)){
                JOptionPane.showMessageDialog(null,"Invalid surname");
                return;
            }
            
 
            String cnic = FatherCNIC1.getText().trim();
            if(!isValidCnic(cnic)){
                JOptionPane.showMessageDialog(null,"Please insert the right cnic number. Use only numbers, no other symbols");
                return;
            }
            
            String birth = DateFormat.getDateInstance().format(DOB.getDate());
            
            String gender;
            if(GMALE.isSelected() && GFEMALE.isSelected()){
                JOptionPane.showMessageDialog(null,"Click at a single gender option");
                return;
            }else{
                gender = GMALE.isSelected() ? "Male" : "Female";
            }
            
            String degree = Degree.getSelectedItem()+"";
            
            double salary = 0;
            try{
                salary = Double.parseDouble(SalaryNew.getText()); 
                if(!(salary>=10000 && salary <= 100000)){
                    JOptionPane.showMessageDialog(null,"Salary should be bewteen 10,000 to 1 lac");
                    return;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Input any amount in nubers");
                return;
            }
            
            String contact = Surname2.getText().trim();
            if(!isValidNum(contact)){
                JOptionPane.showMessageDialog(null,"Please insert the right contact number. Use only numbers, no other symbols");
                return;
            }
            
            String religion = rel.getSelectedItem()+"";
            String nationality = Nationality.getText().trim();
            if(!isValidText(nationality)){
                JOptionPane.showMessageDialog(null,"Invalid nationality");
                return;
            }
            
            String desig = Designation.getSelectedItem()+"";
            String id = "GSR-00-0"+(staff.size()+deactive.size()+1); 
                    
            Staff mem = new Staff(name,father,surname,cnic,birth,gender,"",religion,nationality,degree,contact,salary,desig,id);
            staff.add(mem);
            saveMembersToFile();
            new Page.Staff().setVisible(true);
            this.dispose();
 
        }
      

    }//GEN-LAST:event_SaveDataActionPerformed

    private boolean isValidText(String text){
        for(int i=0;i<text.length();i++){
            char x = text.charAt(i);
            if(!((x>='a' && x<='z' || (x>='A' && x<='Z') || x ==' '))){
                return false;
            }
        }
        return true;
    }
    
    private boolean isValidCnic(String cnic){
        if(cnic.length() != 13){
            return false;
        }
        for(int i=0;i<cnic.length();i++){
            if (!(cnic.charAt(i)>='0' && cnic.charAt(i)<='9')){
                return false;
            }
        }
        return true;
    }
    
    private boolean isValidNum(String num){
        if(num.length() != 11){
            return false;
        }
        for(int i=0;i<num.length();i++){
            if (!(num.charAt(i)>='0' && num.charAt(i)<='9')){
                return false;
            }
        }
        return true;
    }
    
    
    private void DegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegreeActionPerformed

    }//GEN-LAST:event_DegreeActionPerformed

    private void EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIDActionPerformed

    private void SearchEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeeIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchEmployeeIDActionPerformed

    private void SCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCActionPerformed

    private void NameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameEditActionPerformed

    private void TeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherIDActionPerformed

    private void FatherNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameEditActionPerformed

    private void SurnameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameEditActionPerformed

    private void CNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNICActionPerformed

    private void GFEMALE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GFEMALE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GFEMALE1ActionPerformed

    private void Degree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Degree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Degree1ActionPerformed

    private void ContactEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactEditActionPerformed

    private void Nationality1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nationality1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nationality1ActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void SaveEditedDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEditedDataActionPerformed
        // TODO add your handling code here:
        if(TeacherID.getText() == null || NameEdit.getText() == null
                || FatherNameEdit.getText() == null || SurnameEdit.getText() == null
                || CNIC.getText() == null || !DOBEdit.isEnabled()
                || (!GMALE1.isSelected() && !GFEMALE1.isSelected()) || Salary.getText() == null
                || ContactEdit.getText() == null || Nationality1.getText() == null) {
            JOptionPane.showMessageDialog(null,"Please insert all fields");
            return;
        }
        else{
            String id = TeacherID.getText();
            Page.sms.Staff obj = null;
            for(int i=0;i<staff.size();i++){
                if(id.equals(staff.get(i).getId())){
                    obj = staff.get(i);
                    break;
                }
            }
            
            if(obj == null){
                JOptionPane.showMessageDialog(null,"No Employee found with gven id");
                return;
            }
            
            String name = NameEdit.getText();
            if(!isValidText(name)){
                JOptionPane.showMessageDialog(null,"Invalid name");
                return;
            }
            
            String father = FatherNameEdit.getText().trim();
            if(!isValidText(father)){
                JOptionPane.showMessageDialog(null,"Invalid father name");
                return;
            }
            
            String surname = SurnameEdit.getText().trim();
            if(!isValidText(surname)){
                JOptionPane.showMessageDialog(null,"Invalid surname");
                return;
            }
            
            String cnic = CNIC.getText().trim();
            if(!isValidCnic(cnic)){
                JOptionPane.showMessageDialog(null,"Please insert the right cnic number. Use only numbers, no other symbols");
                return;
            }
            
            String birth = DateFormat.getDateInstance().format(DOBEdit.getDate());
            
            String gender;
            if(GMALE1.isSelected() && GFEMALE1.isSelected()){
                JOptionPane.showMessageDialog(null,"Click at a single gender option");
                return;
            }
            else if(GMALE1.isSelected()){
                gender =  GMALE1.getText();
            }
            else if(GFEMALE1.isSelected()){
                gender = GFEMALE1.getText();
            }
            else{
                 JOptionPane.showMessageDialog(null,"Click at a single gender option");
                 return;   
              }
            
            String degree = Degree1.getSelectedItem() + "";
            double salary = 0;
            try{
                salary = Double.parseDouble(Salary.getText().trim());
                if(!(salary >= 10000 && salary <= 100000)){
                    JOptionPane.showMessageDialog(null,"Salary should be in between 10,000 and 1 lac");
                    return;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"put numbers only in salary");
                return;
            }
            
            String contact = ContactEdit.getText().trim();
            if(!isValidNum(contact)){
                JOptionPane.showMessageDialog(null,"Please insert the right contact number. Use only numbers, no other symbols");
                return;
            }
            
            String nationality = Nationality1.getText().trim();
            if(!isValidText(nationality)){
                JOptionPane.showMessageDialog(null,"Invalid Nationality");
                return;
            }
            
            String religion = relEdit.getSelectedItem() + "";
            
            for(int i=0;i<staff.size();i++){
                if(staff.get(i).getId().equals(id)){
                    staff.get(i).setName(name);
                    staff.get(i).setFather(father);
                    staff.get(i).setSurname(surname);
                    staff.get(i).setCnic(cnic);
                    staff.get(i).setSalary(salary);
                    staff.get(i).setBirthDate(birth);
                    staff.get(i).setDegree(degree);
                    staff.get(i).setContact(contact);
                    staff.get(i).setGender(gender);
                    staff.get(i).setNationality(nationality);
                    staff.get(i).setReligion(religion);
                }
            }
            
            saveEditMembersToFile();
            this.dispose();
            new Page.Staff().setVisible(true);
        }
    }//GEN-LAST:event_SaveEditedDataActionPerformed

    private void SearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmpActionPerformed
            Forms.setSelectedIndex(2);
    }//GEN-LAST:event_SearchEmpActionPerformed

    private void DeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmpActionPerformed
          Forms.setSelectedIndex(1);
    }//GEN-LAST:event_DeleteEmpActionPerformed

    private void EditStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStdActionPerformed
          Forms.setSelectedIndex(3);
    }//GEN-LAST:event_EditStdActionPerformed

    private void GenerateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateListActionPerformed
          Forms.setSelectedIndex(4);
    }//GEN-LAST:event_GenerateListActionPerformed

    private void StatisticReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticReportActionPerformed
         Forms.setSelectedIndex(5);
    }//GEN-LAST:event_StatisticReportActionPerformed

    private void SearchEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmpIDActionPerformed
        // TODO add your handling code here:
        
        String id = SearchEmployeeID.getText();
        
        try(FileInputStream file2 = new FileInputStream("Staff.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2)){
            boolean endOfFile = false;
            
            while(!endOfFile){
                try{
                   Staff obj =(Staff) inputFile2.readObject();
                   
                        
                   String sid = obj.getId()+"";
                   
                   if(sid.equals(id)){
                        new SearchStaff(obj);
                        return;
                   }
                }
                catch(EOFException e){
                   endOfFile = true;
                }
                catch(Exception e){
                   // JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(IOException e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
        }
          
        JOptionPane.showMessageDialog(null,"No respective member");
    }//GEN-LAST:event_SearchEmpIDActionPerformed

    private void SearchCNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCNICActionPerformed
        // TODO add your handling code here:
        
        String id = SC.getText();
        
        try(FileInputStream file2 = new FileInputStream("Staff.dat");
            ObjectInputStream inputFile2 = new ObjectInputStream(file2)){
            boolean endOfFile = false;
            
            while(!endOfFile){
                try{
                   Staff obj =(Staff) inputFile2.readObject();
                   String sid = obj.getCnic();
                   
                   if(sid.equals(id)){
                        new SearchStaff(obj);
                        return;
                   }
                }
                catch(EOFException e){
                   endOfFile = true;
                }
                catch(Exception e){
                   // JOptionPane.showMessageDialog(null,e.getMessage());
                }
            }
        }
        catch(IOException e){
            //JOptionPane.showMessageDialog(null,e.getMessage());
        }
          
        JOptionPane.showMessageDialog(null,"No respective member");
    }//GEN-LAST:event_SearchCNICActionPerformed

    private void DeleteEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmployeeButtonActionPerformed
        // TODO add your handling code here:
        String id = EmployeeID.getText();
        for(int i=0;i<staff.size();i++){
            if(staff.get(i).getId().equals(id)){
                deactive.add(staff.get(i));
                staff.remove(i);
                saveDeactiveEmployeesToFile();
                saveMembersToFile();
                return;
            }
        }
    }//GEN-LAST:event_DeleteEmployeeButtonActionPerformed

    private void GenederRatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenederRatioActionPerformed
        int male = 0, female = 0; 
        String gender;
            try{
                for(int i=0; i<staff.size(); i++){
                gender = staff.get(i).getGender();
                
                    if(gender.equals("Male"))
                        male++;
                    else if(gender.equals("Female"))
                        female++;
                
                }
             int total = male+female;
             double percentFemale = (female*100)/total;
             double percentMale = (male*100)/total;
             GenderRatio frame1 = new GenderRatio(); 
             frame1.setFemalePercent(percentFemale);
             frame1.setMalePercent(percentMale);
             frame1.GenerateChart();
            } catch(Exception e){
                }
         
    }//GEN-LAST:event_GenederRatioActionPerformed

    private void ReligionRatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReligionRatioActionPerformed
         int islam=0,hindu=0,christ=0,other=0;    
         String religion;
         for(int i=0; i<staff.size();i++){
              religion = staff.get(i).getReligion();
            switch (religion) {
                case "Islam":
                    islam++;
                    break;
                case "Hindu":
                    hindu++;
                    break;
                case "Christianity":
                    christ++;
                    break;
                case "Other":
                    other++;
                    break;
                default:
                    break;
            }
        }
            
         ReligionRatio frame1 = new ReligionRatio();
         frame1.religionRatio(islam, hindu, christ, other);
       

    }//GEN-LAST:event_ReligionRatioActionPerformed

    private void DegreeRatioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegreeRatioActionPerformed
        int ms = 0, bs =0, phd = 0, mphil = 0;
        for(int i=0; i<staff.size(); i++){
        //BS, MS, Mphil, PhD
            if(staff.get(i).getDegree().equals("BS"))
                bs++;
            else  if(staff.get(i).getDegree().equals("MS"))
                ms++;
            
            else  if(staff.get(i).getDegree().equals("Mphil"))
                mphil++;
            
            else  if(staff.get(i).getDegree().equals("PhD"))
                phd++;
           
        }
        
        
            ReligionRatio frame1 = new ReligionRatio();
            frame1.DegreeChart(bs, ms, mphil, phd);
        
    }//GEN-LAST:event_DegreeRatioActionPerformed

    private void SalaryRtioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryRtioActionPerformed
double [] salary = new double[staff.size()];
        int l1 = 0, l2=0 ,l3=0, l4=0, l5=0, l6 =0 ,l7=0, l8=0, l9=0;
        for(int i=0; i<staff.size();i++){
            salary[i] = staff.get(i).getSalary();
        }
        
        for(int i=0; i<salary.length; i++){
            if(salary[i]>= 10000 && salary[i]<20000)
                l1++;
        
            else if(salary[i]>= 20000 && salary[i]<30000)
                l2++;
        
            
            else if(salary[i]>= 30000 && salary[i]<40000)
                l3++;
        
       
            else if(salary[i]>= 40000 && salary[i]<50000)
                l4++;
        
        
            else if(salary[i]>= 50000 && salary[i]<60000)
                l5++;
        
        
            else if(salary[i]>= 60000 && salary[i]<70000)
                l6++;
        
        
            else if(salary[i]>= 70000 && salary[i]<80000)
                l7++;
        
        
            else if(salary[i]>= 80000 && salary[i]<90000)
                l8++;
        
        
        
            else if(salary[i]>= 90000 && salary[i]<100000)
                l9++;
        
        
        }
        
       ClassStrenght frame = new ClassStrenght();
       frame.salaryChart(l1, l2, l3, l4, l5, l6, l7, l8, l9);
       frame.setVisible(true);
        frame.setSize(1000,600); 
        frame.setResizable(false);
            }//GEN-LAST:event_SalaryRtioActionPerformed

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
           /*
            Administrative
Primary Teacher
Middle Teacher
Account Depart:
Examination Depart:
Manual Staff
Driver
        */
        
            String clas = Designation1.getSelectedItem()+"";
            boolean name = NameChecked.isSelected();
            boolean Fathername = FatherNameChecked1.isSelected();
            boolean salary = SalaryChecked1.isSelected();
            boolean contact = ContactChecked1.isSelected();
            boolean religion = ReligionCheck.isSelected();
            ArrayList <String> colName = new ArrayList<String>();
             for(int i=0; i<5; i++){
                switch (i) {
                    case 0:
                        colName.add("Employee ID");
                        break;
                    case 1:
                        if(name){
                            colName.add("Name") ;
                            name = false;
                        }
                        else if(Fathername){
                            colName.add("Father Name");
                            Fathername = false;
                        }
                        
                        else if(salary){
                            colName.add("Salary");
                            salary = false;
                        }
                        
                        else if(contact){
                            colName.add("Contact");
                            contact = false;
                        }
                        
                        
                        else if(religion){
                            colName.add("Religion");
                            religion = false;
                        }      break;
                    case 2:
                        if(name){
                            colName.add("Name") ;
                            name = false;
                        }
                        else if(Fathername){
                            colName.add("Father Name");
                            Fathername = false;
                        }
                        
                        else if(salary){
                            colName.add("Salary");
                            salary = false;
                        }
                        
                        else if(contact){
                            colName.add("Contact");
                            contact = false;
                        }
                        
                        
                        else if(religion){
                            colName.add("Religion");
                            religion = false;
                        }      break;
                    
                    
                    case 3:
                        if(name){
                            colName.add("Name") ;
                            name = false;
                        }
                        else if(Fathername){
                            colName.add("Father Name");
                            Fathername = false;
                        }
                        
                        else if(salary){
                            colName.add("Salary");
                            salary = false;
                        }
                        
                        else if(contact){
                            colName.add("Contact");
                            contact = false;
                        }
                        
                        
                        else if(religion){
                            colName.add("Religion");
                            religion = false;
                        }      break;
                    
                    case 4:
                        if(name){
                            colName.add("Name") ;
                            name = false;
                        }
                        else if(Fathername){
                            colName.add("Father Name");
                            Fathername = false;
                        }
                        
                        else if(salary){
                            colName.add("Salary");
                            salary = false;
                        }
                        
                        else if(contact){
                            colName.add("Contact");
                            contact = false;
                        }
                        
                        
                        else if(religion){
                            colName.add("Religion");
                            religion = false;
                        }      break;
                    default:
                        break;
                }
             
           }//Closing of checking selected items
           //for counting the rows
           ArrayList<String> rows = new ArrayList<String>();
            for(int j=0; j<staff.size(); j++){
                if(staff.get(j).getDesignation().equals(clas)){
                    rows.add(staff.get(j).getId());
                
                }
            }
           
             
           DefaultTableModel model = new DefaultTableModel();
           RecordTable table = new RecordTable();
           table.TABLE.setModel(model);
           model.setColumnCount(colName.size());
           model.setRowCount(rows.size());
           table.TABLE.setGridColor(Color.BLACK);
           
            //Changing the title of Columns/ 
            for(int i=0; i<colName.size(); i++){
                 ChangeName(table.TABLE , i, colName.get(i));
                     int row = 0;
                 //Checking for column and for class then filing the rows
                    if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Employee ID")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getId()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
           
                 else   if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Name")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getName()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
                    else if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Father Name")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getFather()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
                   else if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Salary")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getSalary()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
           
                    else  if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Contact")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getContact()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
           
                else    if(table.TABLE.getColumnModel().getColumn(i).getHeaderValue().equals("Religion")){
                        for(int j=0; j<staff.size(); j++){
                                if(staff.get(j).getDesignation().equals(clas)){
                                
                                    table.TABLE.setValueAt((staff.get(j).getReligion()), row, i);
                                    row++;
                                }
                                
                         }
                    } 
           
            
            }
            
            
            
            
            
            
            
             
             
               table.setVisible(true);
           
           
        
    }//GEN-LAST:event_GenerateActionPerformed

    public void ChangeName(JTable table, int col_index, String col_name){
            table.getColumnModel().getColumn(col_index).setHeaderValue(col_name);
     }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmp;
    private javax.swing.JPanel AddEmpolyee;
    private javax.swing.JLabel BG;
    private javax.swing.JTextField CNIC;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Contact1;
    private javax.swing.JCheckBox ContactChecked1;
    private javax.swing.JTextField ContactEdit;
    private com.toedter.calendar.JDateChooser DOB;
    private com.toedter.calendar.JDateChooser DOBEdit;
    private javax.swing.JPanel DeactiveEmployee;
    private javax.swing.JComboBox<String> Degree;
    private javax.swing.JComboBox<String> Degree1;
    private javax.swing.JButton DegreeRatio;
    private javax.swing.JLabel Delemp;
    private javax.swing.JButton DeleteEmp;
    private javax.swing.JButton DeleteEmployeeButton;
    private javax.swing.JComboBox<String> Designation;
    private javax.swing.JComboBox<String> Designation1;
    private javax.swing.JPanel EditEmplpyee;
    private javax.swing.JLabel EditLine;
    private javax.swing.JButton EditStd;
    private javax.swing.JTextField EmployeeID;
    private javax.swing.JTextField FatherCNIC1;
    private javax.swing.JTextField FatherName;
    private javax.swing.JCheckBox FatherNameChecked1;
    private javax.swing.JTextField FatherNameEdit;
    private javax.swing.JTextField FirstName;
    public javax.swing.JTabbedPane Forms;
    private javax.swing.JRadioButton GFEMALE;
    private javax.swing.JRadioButton GFEMALE1;
    private javax.swing.JLabel GLine;
    private javax.swing.JRadioButton GMALE;
    private javax.swing.JRadioButton GMALE1;
    private javax.swing.JButton GenederRatio;
    private javax.swing.JButton Generate;
    private javax.swing.JButton GenerateList;
    private javax.swing.JPanel GenerateListEmployee;
    private javax.swing.JPanel HideBar;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton Logout1;
    private javax.swing.JLabel Menu;
    private javax.swing.JCheckBox NameChecked;
    private javax.swing.JTextField NameEdit;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField Nationality1;
    private javax.swing.JCheckBox ReligionCheck;
    private javax.swing.JButton ReligionRatio;
    private javax.swing.JTextField SC;
    private javax.swing.JTextField Salary;
    private javax.swing.JCheckBox SalaryChecked1;
    private javax.swing.JTextField SalaryNew;
    private javax.swing.JButton SalaryRtio;
    private javax.swing.JButton SaveData;
    private javax.swing.JButton SaveEditedData;
    private javax.swing.JLabel Search;
    private javax.swing.JButton SearchCNIC;
    private javax.swing.JButton SearchEmp;
    private javax.swing.JButton SearchEmpID;
    private javax.swing.JPanel SearchEmployee;
    private javax.swing.JTextField SearchEmployeeID;
    private javax.swing.JLabel SearchLine;
    private javax.swing.JButton StatisticReport;
    private javax.swing.JPanel StatisticalReport;
    private javax.swing.JButton StudentPortal;
    private javax.swing.JTextField Surname1;
    private javax.swing.JTextField Surname2;
    private javax.swing.JTextField SurnameEdit;
    private javax.swing.JTextField TeacherID;
    private javax.swing.JLabel addemp;
    private javax.swing.JLabel addempLine;
    private javax.swing.JLabel delLine;
    private javax.swing.JLabel editEmp;
    private javax.swing.JLabel generateList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lgout;
    private javax.swing.JComboBox<String> rel;
    private javax.swing.JComboBox<String> relEdit;
    private javax.swing.JLabel stf;
    // End of variables declaration//GEN-END:variables
}
