/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Page;

public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Search = new javax.swing.JLabel();
        SearchEmp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        GLine = new javax.swing.JLabel();
        addemp = new javax.swing.JLabel();
        addempLine = new javax.swing.JLabel();
        AddEmp = new javax.swing.JButton();
        EditLine = new javax.swing.JLabel();
        delLine = new javax.swing.JLabel();
        SearchLine = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editEmp = new javax.swing.JLabel();
        Delemp = new javax.swing.JLabel();
        generateList = new javax.swing.JLabel();
        GenerateList = new javax.swing.JButton();
        DeleteEmp = new javax.swing.JButton();
        EditStd = new javax.swing.JButton();
        StatisticReport = new javax.swing.JButton();
        lgout = new javax.swing.JLabel();
        Logout1 = new javax.swing.JButton();
        stf = new javax.swing.JLabel();
        StudentPortal = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Protal");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 700));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("              MENU");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 50));

        Search.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("       SEARCH EMPLOYEE");
        Search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        SearchEmp.setBackground(new java.awt.Color(51, 51, 51));
        SearchEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        SearchEmp.setForeground(new java.awt.Color(102, 102, 102));
        SearchEmp.setToolTipText("");
        SearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmpActionPerformed(evt);
            }
        });
        jPanel1.add(SearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("        STATISTIC REPORTS");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 50));

        GLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        GLine.setForeground(new java.awt.Color(204, 204, 204));
        GLine.setText("_________________________");
        jPanel1.add(GLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, -1));

        addemp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addemp.setForeground(new java.awt.Color(255, 255, 255));
        addemp.setText("          ADD EMPLOYEE");
        addemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 50));

        addempLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        addempLine.setForeground(new java.awt.Color(204, 204, 204));
        addempLine.setText("_________________________");
        jPanel1.add(addempLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, -1));

        AddEmp.setBackground(new java.awt.Color(51, 51, 51));
        AddEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        AddEmp.setForeground(new java.awt.Color(102, 102, 102));
        AddEmp.setToolTipText("");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });
        jPanel1.add(AddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 50));

        EditLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        EditLine.setForeground(new java.awt.Color(204, 204, 204));
        EditLine.setText("_________________________");
        jPanel1.add(EditLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 200, -1));

        delLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        delLine.setForeground(new java.awt.Color(204, 204, 204));
        delLine.setText("_________________________");
        jPanel1.add(delLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, -1));

        SearchLine.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        SearchLine.setForeground(new java.awt.Color(204, 204, 204));
        SearchLine.setText("_________________________");
        jPanel1.add(SearchLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        jLabel11.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("_________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 200, -1));

        editEmp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        editEmp.setForeground(new java.awt.Color(255, 255, 255));
        editEmp.setText("          EDIT EMPLOYEE");
        editEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(editEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 50));

        Delemp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Delemp.setForeground(new java.awt.Color(255, 255, 255));
        Delemp.setText("    DEACTIVATE EMPLOYEE");
        Delemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Delemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 50));

        generateList.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        generateList.setForeground(new java.awt.Color(255, 255, 255));
        generateList.setText("          GENERATE LIST");
        generateList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(generateList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 50));

        GenerateList.setBackground(new java.awt.Color(51, 51, 51));
        GenerateList.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        GenerateList.setForeground(new java.awt.Color(102, 102, 102));
        GenerateList.setToolTipText("");
        GenerateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateListActionPerformed(evt);
            }
        });
        jPanel1.add(GenerateList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 50));

        DeleteEmp.setBackground(new java.awt.Color(51, 51, 51));
        DeleteEmp.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        DeleteEmp.setForeground(new java.awt.Color(102, 102, 102));
        DeleteEmp.setToolTipText("");
        DeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmpActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 50));

        EditStd.setBackground(new java.awt.Color(51, 51, 51));
        EditStd.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        EditStd.setForeground(new java.awt.Color(102, 102, 102));
        EditStd.setToolTipText("");
        EditStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStdActionPerformed(evt);
            }
        });
        jPanel1.add(EditStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 50));

        StatisticReport.setBackground(new java.awt.Color(51, 51, 51));
        StatisticReport.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        StatisticReport.setForeground(new java.awt.Color(102, 102, 102));
        StatisticReport.setToolTipText("");
        StatisticReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatisticReportActionPerformed(evt);
            }
        });
        jPanel1.add(StatisticReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 50));

        lgout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lgout.setForeground(new java.awt.Color(255, 255, 255));
        lgout.setText("                  Logout");
        jPanel1.add(lgout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 50));

        Logout1.setBackground(new java.awt.Color(51, 51, 51));
        Logout1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Logout1.setForeground(new java.awt.Color(102, 102, 102));
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });
        jPanel1.add(Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 200, 50));

        stf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        stf.setForeground(new java.awt.Color(255, 255, 255));
        stf.setText("         STUDENT PORTAL");
        jPanel1.add(stf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 50));

        StudentPortal.setBackground(new java.awt.Color(51, 51, 51));
        StudentPortal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        StudentPortal.setForeground(new java.awt.Color(102, 102, 102));
        StudentPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPortalActionPerformed(evt);
            }
        });
        jPanel1.add(StudentPortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 50));

        jLabel13.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("_________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, -1));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/Menu (1).png"))); // NOI18N
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 550));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Page/BGImages/820cce7f-0de0-4906-a734-236b8ae084c1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
            new StaffForms().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_AddEmpActionPerformed

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Logout1ActionPerformed

    private void StudentPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPortalActionPerformed
        
            new Student().setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_StudentPortalActionPerformed

    private void DeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmpActionPerformed
        StaffForms form = new StaffForms();
        form.setVisible(true);
        form.Forms.setSelectedIndex(1);
        this.setVisible(false);
    }//GEN-LAST:event_DeleteEmpActionPerformed

    private void SearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmpActionPerformed
        StaffForms form = new StaffForms();
        form.setVisible(true);
        form.Forms.setSelectedIndex(2);
        this.setVisible(false);
    }//GEN-LAST:event_SearchEmpActionPerformed

    private void EditStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStdActionPerformed
      StaffForms form = new StaffForms();
        form.setVisible(true);
        form.Forms.setSelectedIndex(3);
        this.setVisible(false);
    }//GEN-LAST:event_EditStdActionPerformed

    private void GenerateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateListActionPerformed
         StaffForms form = new StaffForms();
        form.setVisible(true);
        form.Forms.setSelectedIndex(4);
        this.setVisible(false);
    }//GEN-LAST:event_GenerateListActionPerformed

    private void StatisticReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatisticReportActionPerformed
        StaffForms form = new StaffForms();
        form.setVisible(true);
        form.Forms.setSelectedIndex(5);
        this.setVisible(false);
    }//GEN-LAST:event_StatisticReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmp;
    private javax.swing.JLabel Delemp;
    private javax.swing.JButton DeleteEmp;
    private javax.swing.JLabel EditLine;
    private javax.swing.JButton EditStd;
    private javax.swing.JLabel GLine;
    private javax.swing.JButton GenerateList;
    private javax.swing.JButton Logout1;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Search;
    private javax.swing.JButton SearchEmp;
    private javax.swing.JLabel SearchLine;
    private javax.swing.JButton StatisticReport;
    private javax.swing.JButton StudentPortal;
    private javax.swing.JLabel addemp;
    private javax.swing.JLabel addempLine;
    private javax.swing.JLabel delLine;
    private javax.swing.JLabel editEmp;
    private javax.swing.JLabel generateList;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgout;
    private javax.swing.JLabel stf;
    // End of variables declaration//GEN-END:variables
}
